version: "3"

services:
    webapi:
        build:
            context: '.'
        env_file: './.env'
        depends_on:
            - db
        ports:
            - 3000:3000
    db:
        image: postgres:11-alpine
        restart: always
        expose: 
            - "5432"
        environment: 
            POSTGRES_DB: pizza_delivery_test
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        